# Generated by Django 3.2.16 on 2023-01-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20221115_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('gear', 'gear'), ('rider', 'rider'), ('food', 'food'), ('exercise', 'exercise'), ('horse', 'horse'), ('selfcare', 'selfcare')], default='horse', max_length=30),
        ),
    ]
